[features]
seeds = false
skip-lint = false

[programs.localnet]
agent_vault = "66VGaTF2qqogyAC6jczwepjk3C6i5QAe8YQ4mFHveC4b"

[programs.devnet]
agent_vault = "66VGaTF2qqogyAC6jczwepjk3C6i5QAe8YQ4mFHveC4b"

[programs.mainnet]
agent_vault = "66VGaTF2qqogyAC6jczwepjk3C6i5QAe8YQ4mFHveC4b"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/*"]
